package com.cryptora.securechat.core.security

import com.cryptora.securechat.core.common.Constants
import com.cryptora.securechat.domain.model.crypto.CryptoException
import com.cryptora.securechat.domain.model.crypto.EncryptedEnvelope
import java.io.InputStream
import java.io.OutputStream
import java.nio.ByteBuffer
import java.nio.charset.StandardCharsets
import java.security.KeyFactory
import java.security.PrivateKey
import java.security.PublicKey
import java.security.spec.X509EncodedKeySpec
import java.util.Arrays
import java.util.Base64
import javax.crypto.AEADBadTagException
import javax.crypto.BadPaddingException
import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class CryptoManagerImpl @Inject constructor(
    private val keyManager: KeyManager
) : CryptoManager {

    companion object {
        private const val CHUNK_BUFFER_SIZE = 64 * 1024 // 64 KB memory-safe streaming buffer
    }

    override fun encrypt(plaintext: ByteArray, keyAlias: String): ByteArray {
        val secretKey = keyManager.getOrCreateMasterKey(keyAlias)
        return encryptWithKey(plaintext, secretKey)
    }

    override fun decrypt(ciphertextWithIv: ByteArray, keyAlias: String): ByteArray {
        val secretKey = keyManager.getOrCreateMasterKey(keyAlias)
        return decryptWithKey(ciphertextWithIv, secretKey)
    }

    override fun encryptString(plaintext: String, keyAlias: String): String {
        val encryptedBytes = encrypt(plaintext.toByteArray(StandardCharsets.UTF_8), keyAlias)
        return Base64.getEncoder().encodeToString(encryptedBytes)
    }

    override fun decryptString(ciphertextBase64: String, keyAlias: String): String {
        val decodedBytes = Base64.getDecoder().decode(ciphertextBase64)
        val decryptedBytes = decrypt(decodedBytes, keyAlias)
        return String(decryptedBytes, StandardCharsets.UTF_8)
    }

    override fun encryptWithKey(
        plaintext: ByteArray,
        secretKey: SecretKey,
        associatedData: ByteArray?
    ): ByteArray {
        val cipher = Cipher.getInstance(Constants.CIPHER_TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey)

        associatedData?.let { cipher.updateAAD(it) }

        val iv = cipher.iv // 12-byte IV auto-generated by cipher
        val ciphertext = cipher.doFinal(plaintext)

        // Combine [12-byte IV] + [Ciphertext + Auth Tag]
        return ByteBuffer.allocate(iv.size + ciphertext.size)
            .put(iv)
            .put(ciphertext)
            .array()
    }

    override fun decryptWithKey(
        ciphertextWithIv: ByteArray,
        secretKey: SecretKey,
        associatedData: ByteArray?
    ): ByteArray {
        if (ciphertextWithIv.size <= Constants.GCM_IV_LENGTH_BYTES) {
            throw CryptoException.CorruptedCiphertextException("Ciphertext is too short to contain IV and auth tag.")
        }

        try {
            val buffer = ByteBuffer.wrap(ciphertextWithIv)
            val iv = ByteArray(Constants.GCM_IV_LENGTH_BYTES)
            buffer.get(iv)

            val ciphertext = ByteArray(buffer.remaining())
            buffer.get(ciphertext)

            val cipher = Cipher.getInstance(Constants.CIPHER_TRANSFORMATION)
            val spec = GCMParameterSpec(Constants.GCM_TAG_LENGTH_BITS, iv)
            cipher.init(Cipher.DECRYPT_MODE, secretKey, spec)

            associatedData?.let { cipher.updateAAD(it) }

            return cipher.doFinal(ciphertext)
        } catch (e: AEADBadTagException) {
            throw CryptoException.DecryptionFailedException(
                "Integrity authentication tag verification failed. Ciphertext has been modified or wrong key was used.",
                e
            )
        } catch (e: BadPaddingException) {
            throw CryptoException.DecryptionFailedException("Decryption padding or tag error.", e)
        } catch (e: Exception) {
            if (e is CryptoException) throw e
            throw CryptoException.DecryptionFailedException("Decryption failed: ${e.message}", e)
        }
    }

    override fun encryptE2EE(
        plaintext: ByteArray,
        recipientPublicKey: PublicKey,
        keyVersion: Int
    ): EncryptedEnvelope {
        var sharedSecret: ByteArray? = null
        try {
            // 1. Generate single-use ephemeral EC keypair
            val ephemeralPair = keyManager.generateAsymmetricKeyPair()

            // 2. Perform ECDH key agreement
            sharedSecret = keyManager.deriveSharedSecret(ephemeralPair.private, recipientPublicKey)

            // 3. Derive 256-bit AES message key using HKDF-SHA256
            val contentKey = keyManager.deriveKeyHkdf(
                sharedSecret = sharedSecret,
                info = "Cryptora-E2EE-v$keyVersion".toByteArray(StandardCharsets.UTF_8)
            )

            // 4. Encrypt plaintext via AES-256-GCM
            val cipher = Cipher.getInstance(Constants.CIPHER_TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, contentKey)

            val iv = cipher.iv
            val ciphertext = cipher.doFinal(plaintext)

            return EncryptedEnvelope(
                ciphertextBase64 = Base64.getEncoder().encodeToString(ciphertext),
                ivBase64 = Base64.getEncoder().encodeToString(iv),
                keyVersion = keyVersion,
                algorithm = "AES-256-GCM",
                ephemeralPublicKeyBase64 = Base64.getEncoder().encodeToString(ephemeralPair.public.encoded)
            )
        } catch (e: Exception) {
            if (e is CryptoException) throw e
            throw CryptoException.InvalidKeyException("E2EE encryption failed: ${e.message}", e)
        } finally {
            sharedSecret?.let { wipe(it) }
        }
    }

    override fun decryptE2EE(
        envelope: EncryptedEnvelope,
        recipientPrivateKey: PrivateKey,
        expectedKeyVersion: Int?
    ): ByteArray {
        if (expectedKeyVersion != null && envelope.keyVersion != expectedKeyVersion) {
            throw CryptoException.KeyVersionMismatchException(
                "Key version mismatch: Envelope version is ${envelope.keyVersion} but expected $expectedKeyVersion"
            )
        }

        val ephemeralPubBase64 = envelope.ephemeralPublicKeyBase64
            ?: throw CryptoException.CorruptedCiphertextException("Missing ephemeral public key in E2EE envelope")

        var sharedSecret: ByteArray? = null
        try {
            // 1. Decode ephemeral public key
            val pubKeyBytes = Base64.getDecoder().decode(ephemeralPubBase64)
            val keyFactory = KeyFactory.getInstance("EC")
            val ephemeralPublicKey = keyFactory.generatePublic(X509EncodedKeySpec(pubKeyBytes))

            // 2. Perform ECDH key agreement
            sharedSecret = keyManager.deriveSharedSecret(recipientPrivateKey, ephemeralPublicKey)

            // 3. Derive 256-bit AES message key using HKDF-SHA256
            val contentKey = keyManager.deriveKeyHkdf(
                sharedSecret = sharedSecret,
                info = "Cryptora-E2EE-v${envelope.keyVersion}".toByteArray(StandardCharsets.UTF_8)
            )

            // 4. Decrypt AES-256-GCM
            val iv = Base64.getDecoder().decode(envelope.ivBase64)
            val ciphertext = Base64.getDecoder().decode(envelope.ciphertextBase64)

            val cipher = Cipher.getInstance(Constants.CIPHER_TRANSFORMATION)
            val spec = GCMParameterSpec(Constants.GCM_TAG_LENGTH_BITS, iv)
            cipher.init(Cipher.DECRYPT_MODE, contentKey, spec)

            return cipher.doFinal(ciphertext)
        } catch (e: AEADBadTagException) {
            throw CryptoException.DecryptionFailedException(
                "E2EE tag verification failed. Ciphertext has been modified or wrong recipient private key used.",
                e
            )
        } catch (e: Exception) {
            if (e is CryptoException) throw e
            throw CryptoException.DecryptionFailedException("E2EE decryption failed: ${e.message}", e)
        } finally {
            sharedSecret?.let { wipe(it) }
        }
    }

    override fun encryptStream(
        inputStream: InputStream,
        outputStream: OutputStream,
        keyAlias: String
    ): Long {
        val secretKey = keyManager.getOrCreateMasterKey(keyAlias)
        return encryptStreamWithKey(inputStream, outputStream, secretKey)
    }

    override fun decryptStream(
        inputStream: InputStream,
        outputStream: OutputStream,
        keyAlias: String
    ): Long {
        val secretKey = keyManager.getOrCreateMasterKey(keyAlias)
        return decryptStreamWithKey(inputStream, outputStream, secretKey)
    }

    override fun encryptStreamWithKey(
        inputStream: InputStream,
        outputStream: OutputStream,
        secretKey: SecretKey
    ): Long {
        val cipher = Cipher.getInstance(Constants.CIPHER_TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey)

        val iv = cipher.iv
        outputStream.write(iv)
        var totalBytesWritten = iv.size.toLong()

        val buffer = ByteArray(CHUNK_BUFFER_SIZE)
        var bytesRead: Int
        try {
            while (inputStream.read(buffer).also { bytesRead = it } != -1) {
                val chunk = cipher.update(buffer, 0, bytesRead)
                if (chunk != null && chunk.isNotEmpty()) {
                    outputStream.write(chunk)
                    totalBytesWritten += chunk.size
                }
            }

            val finalBytes = cipher.doFinal()
            if (finalBytes != null && finalBytes.isNotEmpty()) {
                outputStream.write(finalBytes)
                totalBytesWritten += finalBytes.size
            }
            outputStream.flush()
            return totalBytesWritten
        } finally {
            wipe(buffer)
        }
    }

    override fun decryptStreamWithKey(
        inputStream: InputStream,
        outputStream: OutputStream,
        secretKey: SecretKey
    ): Long {
        val iv = ByteArray(Constants.GCM_IV_LENGTH_BYTES)
        val ivBytesRead = inputStream.read(iv)
        if (ivBytesRead != Constants.GCM_IV_LENGTH_BYTES) {
            throw CryptoException.CorruptedCiphertextException("Incomplete IV header in encrypted stream")
        }

        val cipher = Cipher.getInstance(Constants.CIPHER_TRANSFORMATION)
        val spec = GCMParameterSpec(Constants.GCM_TAG_LENGTH_BITS, iv)
        cipher.init(Cipher.DECRYPT_MODE, secretKey, spec)

        var totalBytesWritten = 0L
        val buffer = ByteArray(CHUNK_BUFFER_SIZE)
        var bytesRead: Int
        try {
            while (inputStream.read(buffer).also { bytesRead = it } != -1) {
                val chunk = cipher.update(buffer, 0, bytesRead)
                if (chunk != null && chunk.isNotEmpty()) {
                    outputStream.write(chunk)
                    totalBytesWritten += chunk.size
                }
            }

            val finalBytes = cipher.doFinal()
            if (finalBytes != null && finalBytes.isNotEmpty()) {
                outputStream.write(finalBytes)
                totalBytesWritten += finalBytes.size
            }
            outputStream.flush()
            return totalBytesWritten
        } catch (e: AEADBadTagException) {
            throw CryptoException.DecryptionFailedException("Attachment stream integrity check failed (bad auth tag)", e)
        } catch (e: Exception) {
            if (e is CryptoException) throw e
            throw CryptoException.DecryptionFailedException("Failed to decrypt attachment stream: ${e.message}", e)
        } finally {
            wipe(buffer)
        }
    }

    override fun wipe(vararg byteArrays: ByteArray) {
        for (arr in byteArrays) {
            Arrays.fill(arr, 0.toByte())
        }
    }
}
